16-09-17 07:17:29 homeassistant.core: BusHandler:Exception doing job
Traceback (most recent call last):
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/core.py", line 865, in job_handler
    func(*args)
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/core.py", line 730, in _execute_service
    service(call)
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/core.py", line 586, in __call__
    self.func(call)
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/components/light/__init__.py", line 237, in handle_light_service
    light.turn_on(**params)
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/components/light/hue.py", line 253, in turn_on
    *(int(val) for val in kwargs[ATTR_RGB_COLOR]))
TypeError: color_RGB_to_xy() missing 1 required positional argument: 'iB'
16-09-17 15:16:10 homeassistant.components.light.hue: Cannot reach the bridge
Traceback (most recent call last):
  File "/srv/hass/lib/python3.4/site-packages/homeassistant/components/light/hue.py", line 123, in update_lights
    api = bridge.get_api()
  File "/home/hass/.homeassistant/deps/phue.py", line 615, in get_api
    return self.request('GET', '/api/' + self.username)
  File "/home/hass/.homeassistant/deps/phue.py", line 469, in request
    result = connection.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1227, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 348, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
